default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV["DB_PORT"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DB_FOR_DEV"] %>

test:
  <<: *default
  database: <%= ENV["DB_FOR_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DB_FOR_PROD"] %>
